### ISSUE TITLE
Irrelevant usage example (checkout action is missing, target_branch value is invalid)

### ISSUE THREAD

**Issue by nifadyev** [adolfosilva/gh-large-pr-check#1]
Hey

Thank you for such action, great work. I adopted you action to my project needs but the action required some tweaking.

Working usage example:

```yaml
name: Validate Pull Request

on: [pull_request]

jobs:
  check-pr-diff:
    runs-on: ubuntu-latest

    steps:
      # This step is added
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PR diff size
      - uses: adolfosilva/gh-large-pr-check@v1.0.0
        with:
          # This line is changed
          target_branch: ${{ github.event.pull_request.base.ref }}
          max_lines_changed: 500
```

If you still use this action, I can easily make PR with necessary changes
